### ISSUE TITLE
A 'lifetime question ...

### ISSUE THREAD

**Issue by oolonek** [earth-metabolome-initiative/emi-monorepo#1]
... we had with Marco.

here 

```rust
impl<'a> TryFrom<&'a str> for FormulaSearchDB {
    type Error = String;

    fn try_from(s: &'a str) -> Result<Self, Self::Error> {
        match s {
            "BIO" => Ok(FormulaSearchDB::Bio),
            "METACYC" => Ok(FormulaSearchDB::Metacyc),
            "CHEBI" => Ok(FormulaSearchDB::Chebi),
            "COCONUT" => Ok(FormulaSearchDB::Coconut),
            "ECOCYCMINE" => Ok(FormulaSearchDB::Ecocycmine),
            "GNPS" => Ok(FormulaSearchDB::Gnps),
            "HMDB" => Ok(FormulaSearchDB::Hmdb),
            "HSDB" => Ok(FormulaSearchDB::Hsdb),
            "KEGG" => Ok(FormulaSearchDB::Kegg),
            "KEGGMINE" => Ok(FormulaSearchDB::Keggmine),
            "KNAPSACK" => Ok(FormulaSearchDB::Knapsack),
            "MACONDA" => Ok(FormulaSearchDB::Maconda),
            "MESH" => Ok(FormulaSearchDB::Mesh),
            "NORMAN" => Ok(FormulaSearchDB::Norman),
            "UNDP" => Ok(FormulaSearchDB::Undp),
            "PLANTCYC" => Ok(FormulaSearchDB::Plantcyc),
            "PUBCHEM" => Ok(FormulaSearchDB::Pubchem),
            "PUBMED" => Ok(FormulaSearchDB::Pubmed),
            "YMDB" => Ok(FormulaSearchDB::Ymdb),
            "YMDBMINE" => Ok(FormulaSearchDB::Ymdbmine),
            "ZINCBIO" => Ok(FormulaSearchDB::Zincbio),
            _ => Err(format!("Unknown formula search db: {}", s)),
        }
    }
}

impl TryFrom<String> for FormulaSearchDB {
    type Error = String;

    fn try_from(s: String) -> Result<Self, Self::Error> {
        FormulaSearchDB::try_from(s.as_str())
    }
}
```

Could you explain us the purpose of this "double" implementation of TryFrom  (one with the lifetime and ref the other with the object itself) ?

**Comment by LucaCappelletti94** [comment]
It is primarily for ease of use. Let's start by breaking down what the different string objects mean:

- `String` is the actual string object. It represents the actual memory that contains the string, which is a Struct with some fields attached to it.
- `&'a String` would be a pointer to an actual string object, so a pointer to a struct.
- `str` would be not a Struct, [but a basic type](https://doc.rust-lang.org/std/primitive.str.html), more akin to an u64 for instance. At run time, you cannot create an str.
- `&'a str` instead would be a pointer to a string basic type. You can always get the underlying str from a String Struct, so when you implement the TryFrom method for `&'a str` you can also implement it trivially for any of the other variants above.

**Comment by oolonek** [comment]
So if I get this right, the second block is somehow redundant ? 
We could just keep the first one since we can get the the underlying str from a String Struct for `&'a str`?  Or is there a reason to explicity implement it ?
