### ISSUE TITLE
Observation and NestedObservation

### ISSUE THREAD

**Issue by oolonek** [earth-metabolome-initiative/emi-monorepo#10]
Instead of having several pictures types per Observation we rather allow a unique picture type per Observation (defined by its Subject) and allow for NestedObservation.

**Comment by LucaCappelletti94** [comment]
Why is this an issue? Isn't this how it currently works? Also pay attention to the nomenclature:

1. Observation is the name of the flat struct
2. NestedObservation is the name of the nested struct which contains the flat struct of the associated IDs.

**Comment by oolonek** [comment]
Allright. Guess its a close then :)
